### Create Admin ###
POST http://localhost:8080/api/admin/register 
Content-Type: application/json

{
      "fullname":"Rohit Singh",
      "email":"rohit21oct85@gmail.com",
      "password":"password"
}

### Login Admin ###
POST http://localhost:8080/api/admin/login 
Content-Type: application/json

{
      "email":"rohit21oct85@gmail.com",
      "password":"password"
}
### Admin Logout ###
POST http://localhost:8080/api/admin/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNDdmODE5NzM3OGNkMTBjMDk4NDRjOCIsInJvbGUiOjEsImlhdCI6MTYzMjEwNjUzMywiZXhwIjoxNjM0Njk4NTMzfQ.yV3OrIk4KdQJyInFL31M0fnWDP75JgsDIRHmYTp-GeA



### Admin Logout ###
GET http://localhost:8080/api/admin/admin-logout/rohit21oct85@gmail.com
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNDdmODE5NzM3OGNkMTBjMDk4NDRjOCIsInJvbGUiOjEsImlhdCI6MTYzMjEwNjUzMywiZXhwIjoxNjM0Njk4NTMzfQ.yV3OrIk4KdQJyInFL31M0fnWDP75JgsDIRHmYTp-GeA


